### ISSUE TITLE
Not compatible with deno-deploy

### ISSUE THREAD

**Issue by andthedropout** [denoland/merch#36]
Cloned this to deploy on deno-deploy and running into this error when I try to load a page:

An error occurred during route handling or page rendering. TypeError: Cannot read properties of null (reading 'useSyncExternalStore')
    at n.useSyncExternalStore (https://esm.sh/stable/react@18.2.0/X-ZS9wcmVhY3QvY29tcGF0/deno/react.mjs:2:6960)
    at Pe (https://esm.sh/v98/swr@2.0.0-beta.6/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0CmUvcHJlYWN0L2NvbXBhdA/deno/swr.mjs:2:3511)
    at https://esm.sh/v98/swr@2.0.0-beta.6/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0CmUvcHJlYWN0L2NvbXBhdA/deno/_internal.js:2:8091
    at https://esm.sh/v98/swr@2.0.0-beta.6/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0CmUvcHJlYWN0L2NvbXBhdA/deno/_internal.js:2:8335
    at useCart (file:///src/utils/data.ts:67:12)
    at Object.Cart (file:///src/islands/Cart.tsx:35:31)
    at https://esm.sh/v98/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.mjs:12:1590
    at T (https://esm.sh/v98/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.mjs:12:1617)
    at T (https://esm.sh/v98/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.mjs:12:2593)
    at T (https://esm.sh/v98/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.mjs:12:1693)

It looks like in Cart.tsx it is depending on SWR that has updated with a breaking change.

**Comment by bdodroid** [comment]
same. Cant even run it locally now.
